<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "Aimeos payments"
 *
 * Auto generated by Extension Builder 2014-12-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Aimeos payments',
	'description' => 'Aimeos TYPO3 payments extension for Aimeos project',
	'category' => 'plugin',
	'author' => 'Aimeos',
	'author_email' => 'aimeos@aimeos.org',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.5.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.99.99',
			'aimeos' => '2.4.0-2.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);